swapi:
  base-url: https://swapi.py4e.com/api
  endpoints:
    people: /people
    planets: /planets
cache:
  cron: 0 0 * * * *

rest:
  base-url: /api/swapi
  endpoints:
    people: /people
    planets: /planets
  pagination:
    default-limit: 500

server:
  port: 8081

logging:
  level:
    root: DEBUG


